# only trigger when push to main and change is for windows11
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - packer/ubuntu18/*
    - ubuntu18-azure-pipline.yml

name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  - group: kvdevops1
  - name: MyBuildNumber
    value: "0.$(Build.BuildNumber)"

pool:
  name: Contoso
  demands:
    - packer

steps:
  - script: |
      packer -version
    displayName: "Verify Packer version"

  - script: |
      packer init .
    displayName: "Initialize Packer"
    workingDirectory: packer/ubuntu18

  - script: |
      packer validate \
        -var="subscription_id=$(main-subscription-id)" \
        -var="tenant_id=$(tenant-id)" \
        -var="client_id=$(client-id)" \
        -var="client_secret=$(client-secret)" \
        -var="sig_image_version=$(MyBuildNumber)" \
        -var="temp_resource_group_name=packer_ubuntu18_$(MyBuildNumber)" \
        .
    displayName: "Validate Packer"
    workingDirectory: packer/ubuntu18

  - script: |
      packer build \
        -var="subscription_id=$(main-subscription-id)" \
        -var="tenant_id=$(tenant-id)" \
        -var="client_id=$(client-id)" \
        -var="client_secret=$(client-secret)" \
        -var="sig_image_version=$(MyBuildNumber)" \
        -var="temp_resource_group_name=packer_ubuntu18_$(MyBuildNumber)" \
        -force \
        .
    displayName: "Build Ubuntu 18.04"
    workingDirectory: packer/ubuntu18
