# only trigger when push to main and change is for windows11
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - packer/windows11/*
    - windows11-azure-pipline.yml

name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  - group: kvdevops1
  - name: MyBuildNumber
    value: "0.$(Build.BuildNumber)"

pool:
  name: Contoso
  demands:
    - packer

steps:
  - script: |
      echo $(hostname)
      echo $(MyBuildNumber)
      # echo $(main-subscription-id)
      # echo $(tenant-id)
      # echo $(client-id)
      # echo $(client-secret)
      # which packer
    displayName: Echo variables

  - script: |
      packer -version
    displayName: "Verify Packer version"

  - script: |
      packer init .
    displayName: "Initialize Packer"
    workingDirectory: packer/windows11

  - script: |
      packer validate \
        -var="subscription_id=$(main-subscription-id)" \
        -var="tenant_id=$(tenant-id)" \
        -var="client_id=$(client-id)" \
        -var="client_secret=$(client-secret)" \
        -var="sig_image_version=$(MyBuildNumber)" \
        -var="temp_resource_group_name=packer_$(Build.BuildNumber)" \
        .
    displayName: "Validate Packer"
    workingDirectory: packer/windows11

  - script: |
      packer build \
        -var="subscription_id=$(main-subscription-id)" \
        -var="tenant_id=$(tenant-id)" \
        -var="client_id=$(client-id)" \
        -var="client_secret=$(client-secret)" \
        -var="sig_image_version=$(MyBuildNumber)" \
        -var="temp_resource_group_name=packer_$(Build.BuildNumber)" \
        -force \
        .
    displayName: "Build Windows 11"
    workingDirectory: packer/windows11

  # - task: PackerBuild@1
  #   displayName: "Build using Packer"
  #   inputs:
  #     templateType: "builtin"
  #     ConnectedServiceName: "terraform"
  #     isManagedImage: true
  #     managedImageName: "gopackers"
  #     location: "westus2"
  #     storageAccountName: "satfstate98722"
  #     azureResourceGroup: "rg-devops"
  #     baseImageSource: "default"
  #     baseImage: "MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:windows"
  #     packagePath: "$(System.DefaultWorkingDirectory)/customizers"
  #     deployScriptPath: "hello.ps1"
  #     additionalBuilderParameters: '{"vm_size":"Standard_D8s_v4"}'

  # - task: PackerBuild@1
  #   displayName: "Build using Packer"
  #   inputs:
  #     ConnectedServiceName: "terraform"
  #     packerVersion: '1.7.7'
  #     customTemplateLocation: '$(System.DefaultWorkingDirectory)/packer'
  #     templateType: 'custom'
  #     location: "westus2"
  #     storageAccountName: "satfstate98722"
  #     azureResourceGroup: "rg-devops"
  #     packagePath: "$(System.DefaultWorkingDirectory)/packer/customizers"
  #     deployScriptPath: "hello.ps1"
  #     additionalBuilderParameters: '{"vm_size":"Standard_D8s_v4"}'
