# only trigger when push to main and change is for windows11
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - packer/windows11/*
      - pipelines/windows11-azure-pipline.yml

name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  - group: kvdevops1
  - name: MyBuildNumber
    value: "0.$(Build.BuildNumber)"

pool:
  name: Contoso
  demands:
    - packer

steps:
  - script: |
      echo $(hostname)
      echo $(MyBuildNumber)
      # echo $(main-subscription-id)
      # echo $(tenant-id)
      # echo $(client-id)
      # echo $(client-secret)
      # which packer
    displayName: Echo variables

  - script: |
      packer -version
    displayName: "Verify Packer version"

  - script: |
      packer init .
    displayName: "Initialize Packer"
    workingDirectory: packer/windows11

  - script: |
      packer validate \
        -var="subscription_id=$(main-subscription-id)" \
        -var="tenant_id=$(tenant-id)" \
        -var="client_id=$(client-id)" \
        -var="client_secret=$(client-secret)" \
        -var="sig_image_version=$(MyBuildNumber)" \
        .
    displayName: "Validate Packer"
    workingDirectory: packer/windows11

  - script: |
      packer build \
        -var="subscription_id=$(main-subscription-id)" \
        -var="tenant_id=$(tenant-id)" \
        -var="client_id=$(client-id)" \
        -var="client_secret=$(client-secret)" \
        -var="sig_image_version=$(MyBuildNumber)" \
        -force \
        .
    displayName: "Build Windows 11"
    workingDirectory: packer/windows11
